version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'CartoDB/frontend-team'
    groups:
      deck-gl:
        patterns:
          - '@deck.gl/*'
      luma-gl:
        patterns:
          - '@luma.gl/*'
      turf:
        patterns:
          - '@turf/*'
      dev-dependencies:
        dependency-type: 'development'
