version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'CartoDB/app-dev-builder-team'
    groups:
      deck-gl:
        patterns:
          - '@deck.gl/*'
      luma-gl:
        patterns:
          - '@luma.gl/*'
      turf:
        patterns:
          - '@turf/*'
      dev-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
