name: CI

on:
  push:
    branches: [main]
    tags: [v*]

  pull_request:
    # FIMXE:
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        # FIXME:
        # node-version: [18.x, 20.x, 22.x]
        node-version: [18.x]

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     # FIXME: Is this necessary?
      #     node-version: ${{ matrix.node-version }}
      #     registry-url: https://npm.pkg.github.com
      #     scope: '@CartoDB'

      # - name: Enable Corepack
      #   run: corepack enable

      # - name: Install
      #   run: yarn install

      # - name: Build
      #   run: yarn build

      # - name: Lint
      #   run: yarn lint

      # - name: Test
      #   run: yarn test

      - name: Get release type
        id: get-release-type
        uses: actions/github-script@v7
        with:
          script: |
            const regex = '/(alpha|beta)/'
            // FIXME:
            // const refName = context.ref.replace('refs/tags/', '')
            const refName = 'v0.0.1-alpha.0'
            const releaseType = (refName.match(regex))[0]
            console.log(`Release type: ${releaseType}`)
            return releaseType

      # - name: Publish release
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npm publish
